### ISSUE TITLE
Instagram embed is stuck on loading as it tries to load the login screen

### ISSUE THREAD

**Issue by chrbongardt** [justinmahar/react-social-media-embed#26] opened 2022-12-30 09:30 UTC
Instagram embed is stuck on loading as it tries to load the login screen. 

![Screenshot 2022-12-30 at 10 29 30](https://user-images.githubusercontent.com/2834466/210055201-d26713c8-4261-4de4-ba3c-680bd80dfbba.png)
![Screenshot 2022-12-30 at 10 29 27](https://user-images.githubusercontent.com/2834466/210055208-343ceaa3-f8ab-40c6-b47b-a3fb20939bc8.png)

**Comment by justinmahar** [comment] 2022-12-30 18:33
Interesting, not able to reproduce this on my end when logged out. Is that Google Chrome?

**Comment by justinmahar** [comment] 2023-01-12 04:39
Closing until further notice.

**Comment by seebass3** [comment] 2023-01-25 02:02
I'm getting the same issue with my website. Thought it might be an Instagram API problem and updated the plugin. Unfortunately, still shows the same errors - "Failed to load resource: the server responded with a status of 403 ()" in the console.

**Comment by smakman** [comment] 2023-01-25 09:20
Not sure if it's related but the Instagram embed won't load anymore when the `captioned` prop is set to `false`. It will throw the following error and keeps showing the loading spinner:

```js
ErrorUtils caught an error:

getInstalledRelatedApps() is only supported in top-level browsing contexts.

Subsequent non-fatal errors won't be logged; see https://fburl.com/debugjs.
```

When `captioned` is set to `true` it works. Same on the demo site.

**Comment by justinmahar** [comment] 2023-01-25 15:43
Looking into it.

**Comment by justinmahar** [comment] 2023-01-25 15:56
This has been resolved. All IG embeds now show a caption no matter what. Seems that IG for whatever reason doesn't appreciate removing that data tag from the embed container, so it's no longer an option through the library. 

The `captioned` prop is still present but now has no effect. Captions or bust!

To get the fix:

```
npm i react-social-media-embed@latest
```

Cheers y'all 🍻

**Closed** 2023-01-25 15:56 UTC

**Comment by chrbongardt** [comment] 2023-01-25 16:02
Thanks! Awesome work dude!

**Comment by Shain-Dholakiya** [comment] 2023-07-10 17:20
Seems like getting rid of captions should be fine. Instagram allows the option when embedding. Can this be added back please

**Comment by matbrgz** [comment] 2023-10-20 02:19
Any idea how to start to implement this?

> Seems like getting rid of captions should be fine. Instagram allows the option when embedding. Can this be added back please @justinmahar

Any idea how to start to implement this? We can PR.

**Comment by justinmahar** [comment] 2024-04-03 15:45
Captions have been reintroduced via the `captioned` prop.

See the live demo here:

https://justinmahar.github.io/react-social-media-embed/?path=/story/embeds-instagramembed--main-example-with-captions
