### ISSUE TITLE
XEmbed not working

### ISSUE THREAD

**Issue by tkentdna** [justinmahar/react-social-media-embed#72] opened 2024-04-05 05:51 UTC
It appears that XEmbed is not working, including in the demo. I merely see the image below with the spinner continuously spinning.

![image](https://github.com/justinmahar/react-social-media-embed/assets/2592681/cbed5250-8b14-4720-b08d-2bd2c5e1cfda)

**Comment by justinmahar** [comment] 2024-04-05 13:58
Hey @tkentdna!

Tried this on my end both on iOS in Chrome, and macOS in Safari, Chrome, and Brave, and it's properly embedding on my end. Sometimes this kind of issue can be caused by a browser extension, or the browser itself (i.e. Brave), blocking the embed script from loading.

Would love more info -- Which browser are you using? Do you have an ad blocker running? Does it work in an incognito tab?

This is the link to the demo: https://justinmahar.github.io/react-social-media-embed/?path=/story/embeds-xembed--main-example

**Comment by tkentdna** [comment] 2024-04-05 22:05
Thanks for your quick response, Justin! 

I'm using Windows 11 and the Microsoft Edge browser Version 123.0.2420.81, and the XEmbed examples will not display for me, including in an InPrivate session (Incognito in Chrome). However, in trying Chrome Version 123.0.6312.106, the examples display fine, including in an Incognito window. Since Edge is based on Chrome, I assumed there should be no issues running it in Edge (but I guess I was wrong!). 

Using the debugger console in Chrome, I see the following warning: **Third-party cookie will be blocked. Learn more in the Issues tab. (react-social-media-embed/:1 )**

Using the debugger console in Edge, I see the following warning: **Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.**

**Comment by justinmahar** [comment] 2024-04-06 14:34
Awesome, thanks for posting an update here! Might help others running into the same issue. 

Closing this for now

Cheers

**Closed by justinmahar** 2024-04-06 14:34 UTC
